spring:
  thymeleaf:
    cache: false
security:
    oauth2:
        client:
            clientId: 325743279414-gs2hsfc5q8eief9t4sq5r22guuhos54t.apps.googleusercontent.com
            clientSecret: hlGYBd4IOUC5uZL9Qc1eyhXY
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false